spring.application.name=eventos
server.port=8080

# PostgreSQL
#spring.datasource.url=jdbc:postgresql://localhost:5432/eventos
#spring.datasource.username=postgres
#spring.datasource.password=franquiles

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# === Configuración de correo para enviar códigos ===
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=eventostfg@gmail.com
spring.mail.password=klrubsqjfqnihhil
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


